var computerNumber = Number(Math.floor(Math.random() * 100) + 1);
var userPreviousNumber = 0;
var percentageWidth, previousPercentWidth;
var output = $("#output");
var progressbar = $("#progressbar");


// Validates input, input must not be a non numeric value
// must be between 1 and 100
// returns true if valid false otherwise
var validateInput = function(input){
		if(input == "" || input === " "){ 
			$("#error").text("Input cannot be empty");
		} else { 
			input = Number(input);
			if(typeof input !== "number" || isNaN(input)){
				$("#error").text("Invalid input");
				return false;
			} else if (input > 100 || input < 1){
				$("#error").text("Input out of range (1 - 100)");
				return false;
			} else {
				$("#error").text("");
				userNumber = input;
				return true;
			}
		}
}

// Generate width percentage in relation to the difference between
// the user number and the computer number
// return the width in percentage as string
var getWidth = function(){
	previousPercentWidth = percentageWidth;
	if(computerNumber === userNumber){
		percentageWidth = 100;
	} else if(userNumber < computerNumber){
		percentageWidth =  Math.floor((userNumber / computerNumber) * 100);
	} else {
		var absoluteDiff = Math.abs(computerNumber - userNumber);
		percentageWidth = (100 - Math.floor((absoluteDiff/userNumber) * 100));
	}
	return percentageWidth + "%";
}


// Gets colour in relation to percentage of the width generated by getWidth()
// returns color generated
var getColor = function(){
	return "rgb(" + percentageWidth + "%,0%, " + (100 - percentageWidth) + "%)";
}


// Sets animation on the progress bar and saves users previous entry
var setAnimation = function(){
	progressbar.animate({width: getWidth(), backgroundColor: getColor()}, "slow");
	userPreviousNumber = userNumber;
}


// To start a new game
var resetGame = function(){
	progressbar.animate({width: "0%", backgroundColor: "blue"}, "slow");
	output.text("");
	userPreviousNumber = 0;
	$("#submit").show();
	$("#userNumber").removeProp("disabled");
	$("#userNumber").focus();
}


// Prints response and plays animation of progress bar
var response = function(){
		setAnimation();	
		if(userPreviousNumber === 0){
			output.html("Getting hot");
		} else if(previousPercentWidth < percentageWidth){
			output.html("Getting hotter!!!");
		} else if(previousPercentWidth > percentageWidth){
			output.html("Getting colder!");
		} else {
			output.html("Not hotter Not colder");
		}
}

// Takes in the computer generated number and 
// compares with the user submitted number
var Game = function (computerNumber){
	// Compares the two numbers if they are equal
	// else get a response of how close or far the user is
	if(computerNumber === userNumber){
		output.html("You guessed right<br>");
		setAnimation();
		$("#submit").hide();
		$("#userNumber").prop("disabled", true);
	} else {
		response();
	}
}


// Gets value from the input form tag
var processGame = function(){
		$("#error").text("");
		input = document.getElementById("userNumber").value;
			if(validateInput(input)){
				Game(computerNumber);
			}
		
		$("#userNumber").val("");
		$("#userNumber").focus();
}


// JQuery action events
$(document).ready(function(){
	$("#userNumber").on("input", function(evt){
		var input = document.getElementById("userNumber").value;
		validateInput(input);
	});
	
	// Listens to submit button click event
	$("#submit").click(function(evt){
		processGame();
	});

	// Listens to Enter keypress event on the input form tag
	$("#userNumber").keypress(function(evt){
		if(evt.keyCode === 13){
			processGame();
		}
	});

	// Listens to new game button click event to reset
	// Generates a new random number for computerNumber for the new game
	$("#newgame").click(function(){
		resetGame();
		computerNumber = Number(Math.floor(Math.random() * 100) + 1);
	})

});