var computerNumber = Number(Math.floor(Math.random() * 100));
var userPreviousNumber = percentageWidth = previousPercentWidth = 0;
var $input = $("#userNumber");
var $output = $("#output");
var $progressbar = $("#progressbar");

// Validates input, input must not be a non numeric value
// must be between 1 and 100 returns true if valid false otherwise
var validateInput = function(input){
		if(input == "" || input === " "){ 
			$("#error").text("Input cannot be empty");
		} else { 
			input = Number(input);
			if(typeof input !== "number" || isNaN(input)){
				$("#error").text("Invalid input");
				return false;
			} else if (input > 100 || input < 0){
				$("#error").text("Input out of range (0 - 100)");
				return false;
			} else {
				$("#error").text("");
				userNumber = input;
				return true;
			}
		}
}

// Generate width percentage in relation to the difference between
// the user number and the computer number return the width in percentage as string
var getWidth = function(){
	previousPercentWidth = percentageWidth;
	Width = Math.max(Math.abs(100 - computerNumber), computerNumber);
	percentageWidth = ((Width - Math.abs(computerNumber - userNumber))/Width) * 100;
	return percentageWidth + "%";
}

// Gets colour in relation to percentage of the width generated by getWidth() returns color generated
var getColor = function(){
	return "rgb(" + percentageWidth + "%,0%, " + (100 - percentageWidth) + "%)";
}

// Sets animation on the progress bar and saves users previous entry
var setAnimation = function(){
	$progressbar.animate({width: getWidth(), backgroundColor: getColor()}, "slow");
	userPreviousNumber = userNumber;
}

// To start a new game
var resetGame = function(){
	userPreviousNumber = percentageWidth = 0;
	$progressbar.animate({width: "0%", backgroundColor: "blue"}, "slow");
	$output.text("");
	$("#error").text("");
	$input.val("");
	$("#submit").show();
	$("#userNumber").removeProp("disabled");
	$("#userNumber").focus();
	$output.html("Waiting for your guess")
}

// Prints response and plays animation of progress bar
var response = function(){	
	getWidth();
	if(userPreviousNumber === 0){
		$output.html("Warming up");
	} else if(previousPercentWidth < percentageWidth){
		$output.html("Getting hotter!!!");
	} else if(previousPercentWidth > percentageWidth){
		$output.html("Getting colder!");
	} else {
		$output.html("Not hotter Not colder");
	}
	setAnimation();	
}

// Takes in the computer generated number and compares with the user submitted number
var Game = function (computerNumber){
	// Compares the two numbers if they are equal else get a response of how close or far the user is
	if(computerNumber === userNumber){
		$output.html("You guessed right<br>");
		setAnimation();
		$("#submit").hide();
		$("#userNumber").prop("disabled", true);
	} else {
		response();
	}
}

var Actions = {
	onReady: function(){
		$("#userNumber").on("input", Actions.onInputValidation);
		
		// Listens to submit button click event
		$("#submit").click(Actions.playGame);

		// Listens to Enter keypress event on the input form tag
		$("#userNumber").keypress(Actions.onKeypressPlayGame);

		// Listens to new game button click event to reset
		// Generates a new random number for computerNumber for the new game
		$("#newgame").click(Actions.onResetButtonClicked);
	},

	onInputValidation: function(){
		validateInput($input.val());
	},

	playGame: 	function(){
		$("#error").text("");
		if(validateInput($input.val())){
			Game(computerNumber);
		}
		$input.val("").focus();
	},

	onKeypressPlayGame: function(evt){
		if(evt.keyCode === 13){
			Actions.playGame();
		}
	},

	onResetButtonClicked: function(){
		resetGame();
		computerNumber = Number(Math.floor(Math.random() * 100) + 1);
	}
}

// JQuery action events
$(document).ready(Actions.onReady);